<html>

<head>
    <style>
        @page {
            margin: 0cm 0cm;
        }

        /** Define now the real margins of every page in the PDF **/
        body {
            background-color: #FFF;
            text-align: justify;
            font-family: system-ui, system-ui, sans-serif;
            background-image: url('https://portal.finvert.io/storage/ThemeFinvert/images/rp_agreement_footer.png');
            background-size: 100% 100%;
        }

        main .content {
            padding-top: 2cm;
            padding-left: 1.3cm;
            padding-right: 1.3cm;
        }

        body p {
            line-height: 24px;
            font-size: 16px;
            margin-bottom: 5px;
        }

        body li {
            line-height: 26px;
            margin-bottom: 15px;
            font-size: 15px;
        }

        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td,
        th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
    </style>
</head>

<body>
    <main>
        <img src="https://portal.finvert.io/storage/ThemeFinvert/images/rp_agreement.png"
            style="width: 100%; height: 1067px;" />
        <div style="page-break-before:always">&nbsp;</div>
        <div class="content">
            <p>This Referral Partnership Agreement (the "Agreement") is entered into on this ......................day
                of...............
                23 by and between Finvert IO LLC , a Payment processing company registered in
                suit 1,a.l.evelyn ltd building, Charlestown Nevis (hereinafter referred to as "Finvert IO"), and
                ...............................................................................................</p>
            <p>(Referral Partner Name),
                ..............................................................................................................................................
            </p>
            <p>(Referral Partner's Business Type) located
                at,................................................................................................................<br /><br />
                ..........................................................................................................................................................................................
            </p>
            <p>(Referral Partner's Address) (hereinafter referred to as the "Referral Partner").</p>
            <p>WHEREAS, {{ config('app.name') }} IO's provides payment processing services and has developed an
                innovative
                payment processing system that
                allows merchants to easily accept and process payments from their customers; and</p>
            <p>WHEREAS, the Referral Partner has contacts with potential customers who may be interested in using
                {{ config('app.name') }} IO's payment processing services; and</p>
            <p>WHEREAS, {{ config('app.name') }} IO's desires to engage the Referral Partner to promote
                {{ config('app.name') }} IO's payment processing services to
                potential customers;</p>
            <h3>NOW, THEREFORE, the parties agree as follows:</h3>
            <h4>Referral Partner Obligations</h4>
            <p>The Referral Partner shall use reasonable efforts to promote and market {{ config('app.name') }} IO's
                payment processing services to
                potential customers. The Referral Partner shall not engage in any activities that would harm the
                reputation of {{ config('app.name') }}
                IO's or its payment processing services.</p>
            <h4>Payment of Referral Fees</h4>
            <p>In consideration of the Referral Partner's efforts, {{ config('app.name') }} IO's shall pay a referral
                fee (the "Referral Fee") to the
                Referral Partner for each new customer referred by the Referral Partner who enters into a contract for
                {{ config('app.name') }} IO's
                payment processing services. The Referral Fee shall be calculated as a percentage of the revenue
                generated by the
                referred customer's use of {{ config('app.name') }} IO's payment processing services. The percentage
                shall be determined by mutual
                agreement between {{ config('app.name') }} IO's and the Referral Partner prior to the referral.</p>
        </div>
        <div style="page-break-before:always">&nbsp;</div>
        <div class="content">
            <h4>Referral Process</h4>
            {{-- <p>The Referral Partner shall provide {{ config('app.name') }} IO's with the name and contact information
                of
                each potential customer referred
                by the Referral Partner. {{ config('app.name') }} IO's shall be solely responsible for following up
                with
                each potential customer and
                closing the sale.
                {{ config('app.name') }} IO's shall notify the Referral Partner of the status of each referral.</p> --}}

            <p>The referral partner shall introduce the potential customer/merchant through desired channels. The
                referral partner is responsible for all the communications with the merchant as long as they have an
                active account with {{ config('app.name') }}.
            </p>

            <h4>Commissions</h4>
            <p>Commissions to be paid to the referral partners on the 15th of every month for the sales generated during
                the previous month. The commission would be the difference between the buy rate and the sell rate
                decided by the referral partner. The partner would receive 100% of the markup added to the buy rate.The
                commissions to the referral partner are to be paid through crypto and the partner will continue to
                receive the commissions as long as the merchant referred is actively processing with Finvert.
            </p>
            <h4>Relationship of the Parties</h4>
            <p>The parties agree that the Referral Partner is an independent contractor and is not an employee or agent
                of {{ config('app.name') }} IO's
                The Referral Partner shall not have the authority to bind {{ config('app.name') }} IO's or make any
                representations on behalf of {{ config('app.name') }}
                IO's</p>
            <h4>Confidentiality</h4>
            <p>The parties agree to maintain the confidentiality of all confidential information provided by the other
                party in
                connection with this Agreement.</p>
            <h4>Term and Termination</h4>
            <p>This Agreement shall remain in effect for an initial term of (term length), and shall automatically renew
                for successive
                (term length) terms unless either party gives notice of termination at least (notice period) days prior
                to the end of
                the then-current term. Either party may terminate this Agreement at any time for any reason upon (notice
                period) days'
                written notice to the other party.</p>
            <h4>Governing Law</h4>
            <p>This Agreement shall be governed by and construed in accordance with the laws of the State of (governing
                law state) without giving effect to the principles of conflict of laws.</p>

        </div>
        <div style="page-break-before:always">&nbsp;</div>
        <div class="content">
            <h4>Entire Agreement</h4>
            <p>This Agreement constitutes the entire agreement between the parties with respect to the subject matter
                hereof and
            </p>
            <P>supersedes all prior negotiations, understandings, and agreements between the parties, whether written
                or oral.</P>
            <h3>Amendments. This Agreement may be amended only by written agreement signed by both parties.</h3>
            <p>Counterparts. This Agreement may be executed in counterparts, each of which shall be deemed an original,
                but all of
                which together shall constitute one and the same instrument.</p>
            <p>IN WITNESS WHEREOF, the parties have executed this Agreement as of the date first above written.</p>

            {{-- <h4>Pricing Structure :</h4>
            <table>
                <tbody>
                    <tr>
                        <td>Add Buy Rate For Visa Card</td>
                        <td>{{ $add_buy_rate }}%</td>
                    </tr>
                    <tr>
                        <td>Add Buy Rate For Master Card</td>
                        <td>{{ $add_buy_rate_master }}%</td>
                    </tr>
                    <tr>
                        <td>Add Buy Rate For Amex Card</td>
                        <td>{{ $add_buy_rate_amex }}%</td>
                    </tr>
                    <tr>
                        <td>Add Buy Rate For Discover Card</td>
                        <td>{{ $add_buy_rate_discover }}%</td>
                    </tr>
                </tbody>
            </table> --}}
        </div>

        <div class="content">
            <div style="width: 100%;">
                <div style="width: 50%; float: left;">
                    <h3>FINVERT IO'S LLC</h3>
                </div>
                <div style="width: 50%; float: left; text-align: right;">
                    <p>_____________________________________(Company)</p>
                </div>
                <div style="clear: both;"></div>
            </div>

            <br /><br />
            <div style="width: 100%;">
                <div style="width: 50%; float: left;">
                    <h3>Position</h3>
                    <span>DIRECTOR</span>
                </div>
                <div style="width: 50%; float: left; text-align: left;">
                    <h3>Position</h3>
                    <p>_____________________________________</p>
                </div>
                <div style="clear: both;"></div>
            </div>

            <br /><br />
            <div style="width: 100%;">
                <div style="width: 50%; float: left;">
                    <h3>Name</h3>
                    <span>MANUEL JOSE</span>
                </div>
                <div style="width: 50%; float: left; text-align: left;">
                    <h3>Name</h3>
                    <p>_____________________________________</p>
                </div>
                <div style="clear: both;"></div>
            </div>
            <br /><br /><br />
            <div style="width: 100%;">
                <div style="width: 50%; float: left;">
                    <div style="position: relative;">
                        <h3>Signature</h3>
                        <img src="https://portal.finvert.io/storage/ThemeFinvert/images/Signature.png"
                            style="width: 150px; position: absolute;left: 0px;" />
                    </div>
                </div>
                <div style="width: 50%; float: left; text-align: left;">
                    <h3>Signature</h3>
                </div>
                <div style="clear: both;"></div>
            </div>
        </div>


        </div>
    </main>
</body>

</html>
